language: android
jdk: oraclejdk8

env:
 global:
   - ANDROID_API_LEVEL=30
   - ANDROID_BUILD_TOOLS_VERSION=30.0.2

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

branches:
  only:
    - develop
    - 0.24.0

android:
 licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
 components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
   # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-$ANDROID_API_LEVEL
   # Android emulator
    - android-22
    - sys-img-armeabi-v7a-android-22

before_install:
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30.0.2"

before_script:
  # Launch emulator before the execution
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - "curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash"

script:
  - ./gradlew dependencies --stacktrace --daemon
  - fossa --no-ansi || true
  - ./gradlew -Pcoverage testFdroidDebugUnitTest --stacktrace --daemon
  - ./gradlew -Pcoverage connectedFdroidDebugAndroidTest --stacktrace --daemon
  - ./gradlew -Pcoverage jacocoTestReport --stacktrace --daemon
  - |
    if [ $TRAVIS_TAG ]; then
      gpg --yes --batch --passphrase=$SERVICES_ENCRYPT_KEY ./app/src/release/google-services.json.gpg;
      gpg --yes --batch --passphrase=$SERVICES_ENCRYPT_KEY ./app/src/release/agconnect-services.json.gpg;
      gpg --yes --batch --passphrase=$ENCRYPT_KEY ./app/key.p12.gpg;
      gpg --yes --batch --passphrase=$ENCRYPT_KEY ./app/upload-key.jks.gpg;
      ./gradlew publishPlayRelease -PenableFirebase --stacktrace;
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)
